CREATE DATABASE IF NOT EXISTS P11;

USE P11;

CREATE TABLE CATEGORIES
(ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
NOM VARCHAR(80),
LINK_OFF VARCHAR(80),
PRIMARY KEY (ID)
)ENGINE=INNODB;

CREATE TABLE PRODUITS(
ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
NOM VARCHAR(200),
URL VARCHAR(150),
NUTRISCORE INT,
CATEGORIE_ID INT UNSIGNED,
PRIMARY KEY (ID),
CONSTRAINT fk_ok
FOREIGN KEY (CATEGORIE_ID) REFERENCES CATEGORIES (ID)
)ENGINE=INNODB;


CREATE TABLE SUBSTITUTS(
ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
PRODUIT_ID INT UNSIGNED,
INPUT_PRODUCT VARCHAR(50),
STORE VARCHAR(300),
PRIMARY KEY (ID),
CONSTRAINT sub_ok
FOREIGN KEY (PRODUIT_ID) REFERENCES PRODUITS (ID)
)ENGINE=INNODB;